[package]
name = "aevum-attestation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
ulid = { workspace = true }
aevum-identity = { path = "../identity" }

[dev-dependencies]
tokio = { workspace = true }
