# cargo-deny — license + advisory gate for WinAevum-Unify (L-38).
# Docs: https://embarkstudios.github.io/cargo-deny/

[graph]
all-features = false
no-default-features = false

[advisories]
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Unlicense",
]
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
