[package]
name = "aevum-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
rand = "0.8"
hex = "0.4"
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
tokio = { workspace = true }
